<?php

/**
 * @file
 * Contains iq_faq.module.
 */

use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_metatags_alter().
 *
 * Read FAQ data from rendered node content and add it to metatags.
 */
function iq_faq_metatags_alter(array &$metatags) {

  foreach (\Drupal::routeMatch()->getParameters()->all() as $entityType => $entity) {

    // Check if entity is object.
    if (!is_object($entity)) {
      continue;
    }

    // Check if view_builder exists for given entity.
    if (!\Drupal::service('entity_type.manager')->hasHandler($entityType, 'view_builder')) {
      continue;
    }

    // Render current page for metatag extraction.
    \Drupal::state()->set('render_for_faq_extraction', TRUE);
    $builder = \Drupal::service('entity_type.manager')->getViewBuilder($entityType);
    $build = $builder->view($entity, 'full');
    $output = \Drupal::service('renderer')->renderPlain($build);
    \Drupal::state()->delete('render_for_faq_extraction');

    $dom = new DOMDocument();
    $dom->loadHTML($output, LIBXML_NOERROR);
    $finder = new DomXPath($dom);

    // Search content for iq-faq-item elements.
    $questions = iterator_to_array($finder->query("//*[contains(concat(' ', normalize-space(@class), ' '), ' iq-faq-item-question ')]"));
    $answers = iterator_to_array($finder->query("//*[contains(concat(' ', normalize-space(@class), ' '), ' iq-faq-item-answer ')]"));

    if (count($questions)) {
      if (array_key_exists('schema_qa_page_main_entity', $metatags)) {
        $schemaFAQ = unserialize($metatags['schema_qa_page_main_entity']);
      }
      else {
        $schemaFAQ = [
          'pivot' => 1,
          '@type' => 'Question',
          'name'  => '',
          'acceptedAnswer' => [
            'pivot' => 1,
            '@type' => 'Answer',
            'text'  => '',
          ],
        ];
      }

      $questions = array_map(function ($question) {
        return trim(strip_tags($question->ownerDocument->saveXML($question)));
      }, $questions);

      $answers = array_map(function ($answer) {
        return trim(strip_tags($answer->ownerDocument->saveXML($answer)));
      }, $answers);

      $schemaFAQ['name'] = trim(implode('::', array_merge(explode('::', trim($schemaFAQ['name'], '::')), $questions)), '::');
      $schemaFAQ['acceptedAnswer']['text'] = trim(implode('::', array_merge(explode('::', trim($schemaFAQ['acceptedAnswer']['text'], '::')), $answers)), '::');
      $schemaFAQ['acceptedAnswer']['url'] = Url::fromRoute('<current>', [], ["absolute" => TRUE])->toString();
      $metatags['schema_qa_page_type'] = 'FAQPage';
      $metatags['schema_qa_page_main_entity'] = serialize($schemaFAQ);
    }
  }
}

/**
 * Implements hook_form_alter().
 *
 * Remove webforms when rendering page for FAQ extraction.
 */
function iq_faq_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if (\Drupal::state()->get('render_for_faq_extraction', FALSE)) {
    if (strpos($form_id, "webform_submission") !== FALSE) {
      $form['#access'] = FALSE;
    }
  }
}
